//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.20 at 11:45:58 AM CEST 
//

package tepisclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScannerMetadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContentItem" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ConceptName">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StainMetadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContentItem" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ConceptName">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Code">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PrimaryAnatomicStructure">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContentItem">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Code">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PixelMetadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NumberOfLevels" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Levels">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PixelLevelMetadata" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="PixelSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PhysicalOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PhysicalSpacing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ScanFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="IsNativeLevel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="IsLossyCompressed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="TileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scannerMetadata",
    "stainMetadata",
    "primaryAnatomicStructure",
    "pixelMetadata"
})
@XmlRootElement(name = "ImageMetadata")
public class ImageMetadata {

    @XmlElement(name = "ScannerMetadata", required = true)
    protected ImageMetadata.ScannerMetadata scannerMetadata;
    @XmlElement(name = "StainMetadata", required = true)
    protected ImageMetadata.StainMetadata stainMetadata;
    @XmlElement(name = "PrimaryAnatomicStructure", required = true)
    protected ImageMetadata.PrimaryAnatomicStructure primaryAnatomicStructure;
    @XmlElement(name = "PixelMetadata", required = true)
    protected ImageMetadata.PixelMetadata pixelMetadata;

    /**
     * Gets the value of the scannerMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ImageMetadata.ScannerMetadata }
     *     
     */
    public ImageMetadata.ScannerMetadata getScannerMetadata() {
        return scannerMetadata;
    }

    /**
     * Sets the value of the scannerMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageMetadata.ScannerMetadata }
     *     
     */
    public void setScannerMetadata(ImageMetadata.ScannerMetadata value) {
        this.scannerMetadata = value;
    }

    /**
     * Gets the value of the stainMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ImageMetadata.StainMetadata }
     *     
     */
    public ImageMetadata.StainMetadata getStainMetadata() {
        return stainMetadata;
    }

    /**
     * Sets the value of the stainMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageMetadata.StainMetadata }
     *     
     */
    public void setStainMetadata(ImageMetadata.StainMetadata value) {
        this.stainMetadata = value;
    }

    /**
     * Gets the value of the primaryAnatomicStructure property.
     * 
     * @return
     *     possible object is
     *     {@link ImageMetadata.PrimaryAnatomicStructure }
     *     
     */
    public ImageMetadata.PrimaryAnatomicStructure getPrimaryAnatomicStructure() {
        return primaryAnatomicStructure;
    }

    /**
     * Sets the value of the primaryAnatomicStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageMetadata.PrimaryAnatomicStructure }
     *     
     */
    public void setPrimaryAnatomicStructure(ImageMetadata.PrimaryAnatomicStructure value) {
        this.primaryAnatomicStructure = value;
    }

    /**
     * Gets the value of the pixelMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ImageMetadata.PixelMetadata }
     *     
     */
    public ImageMetadata.PixelMetadata getPixelMetadata() {
        return pixelMetadata;
    }

    /**
     * Sets the value of the pixelMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageMetadata.PixelMetadata }
     *     
     */
    public void setPixelMetadata(ImageMetadata.PixelMetadata value) {
        this.pixelMetadata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NumberOfLevels" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Levels">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PixelLevelMetadata" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="PixelSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PhysicalOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PhysicalSpacing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ScanFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="IsNativeLevel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="IsLossyCompressed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="TileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numberOfLevels",
        "levels"
    })
    public static class PixelMetadata {

        @XmlElement(name = "NumberOfLevels")
        protected int numberOfLevels;
        @XmlElement(name = "Levels", required = true)
        protected ImageMetadata.PixelMetadata.Levels levels;

        /**
         * Gets the value of the numberOfLevels property.
         * 
         */
        public int getNumberOfLevels() {
            return numberOfLevels;
        }

        /**
         * Sets the value of the numberOfLevels property.
         * 
         */
        public void setNumberOfLevels(int value) {
            this.numberOfLevels = value;
        }

        /**
         * Gets the value of the levels property.
         * 
         * @return
         *     possible object is
         *     {@link ImageMetadata.PixelMetadata.Levels }
         *     
         */
        public ImageMetadata.PixelMetadata.Levels getLevels() {
            return levels;
        }

        /**
         * Sets the value of the levels property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageMetadata.PixelMetadata.Levels }
         *     
         */
        public void setLevels(ImageMetadata.PixelMetadata.Levels value) {
            this.levels = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PixelLevelMetadata" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="PixelSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PhysicalOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PhysicalSpacing" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ScanFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="IsNativeLevel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="IsLossyCompressed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="TileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pixelLevelMetadata"
        })
        public static class Levels {

            @XmlElement(name = "PixelLevelMetadata", required = true)
            protected List<ImageMetadata.PixelMetadata.Levels.PixelLevelMetadata> pixelLevelMetadata;

            /**
             * Gets the value of the pixelLevelMetadata property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pixelLevelMetadata property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPixelLevelMetadata().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ImageMetadata.PixelMetadata.Levels.PixelLevelMetadata }
             * 
             * 
             */
            public List<ImageMetadata.PixelMetadata.Levels.PixelLevelMetadata> getPixelLevelMetadata() {
                if (pixelLevelMetadata == null) {
                    pixelLevelMetadata = new ArrayList<ImageMetadata.PixelMetadata.Levels.PixelLevelMetadata>();
                }
                return this.pixelLevelMetadata;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="PixelSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PhysicalOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PhysicalSpacing" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ScanFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="IsNativeLevel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="IsLossyCompressed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="TileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "level",
                "pixelSize",
                "physicalOrigin",
                "physicalSpacing",
                "scanFactor",
                "isNativeLevel",
                "isLossyCompressed",
                "tileSize"
            })
            public static class PixelLevelMetadata {

                @XmlElement(name = "Level")
                protected int level;
                @XmlElement(name = "PixelSize", required = true)
                protected String pixelSize;
                @XmlElement(name = "PhysicalOrigin", required = true)
                protected String physicalOrigin;
                @XmlElement(name = "PhysicalSpacing", required = true)
                protected String physicalSpacing;
                @XmlElement(name = "ScanFactor")
                protected double scanFactor;
                @XmlElement(name = "IsNativeLevel")
                protected boolean isNativeLevel;
                @XmlElement(name = "IsLossyCompressed")
                protected boolean isLossyCompressed;
                @XmlElement(name = "TileSize", required = true)
                protected String tileSize;

                /**
                 * Gets the value of the level property.
                 * 
                 */
                public int getLevel() {
                    return level;
                }

                /**
                 * Sets the value of the level property.
                 * 
                 */
                public void setLevel(int value) {
                    this.level = value;
                }

                /**
                 * Gets the value of the pixelSize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPixelSize() {
                    return pixelSize;
                }

                /**
                 * Sets the value of the pixelSize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPixelSize(String value) {
                    this.pixelSize = value;
                }

                /**
                 * Gets the value of the physicalOrigin property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhysicalOrigin() {
                    return physicalOrigin;
                }

                /**
                 * Sets the value of the physicalOrigin property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhysicalOrigin(String value) {
                    this.physicalOrigin = value;
                }

                /**
                 * Gets the value of the physicalSpacing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhysicalSpacing() {
                    return physicalSpacing;
                }

                /**
                 * Sets the value of the physicalSpacing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhysicalSpacing(String value) {
                    this.physicalSpacing = value;
                }

                /**
                 * Gets the value of the scanFactor property.
                 * 
                 */
                public double getScanFactor() {
                    return scanFactor;
                }

                /**
                 * Sets the value of the scanFactor property.
                 * 
                 */
                public void setScanFactor(double value) {
                    this.scanFactor = value;
                }

                /**
                 * Gets the value of the isNativeLevel property.
                 * 
                 */
                public boolean isIsNativeLevel() {
                    return isNativeLevel;
                }

                /**
                 * Sets the value of the isNativeLevel property.
                 * 
                 */
                public void setIsNativeLevel(boolean value) {
                    this.isNativeLevel = value;
                }

                /**
                 * Gets the value of the isLossyCompressed property.
                 * 
                 */
                public boolean isIsLossyCompressed() {
                    return isLossyCompressed;
                }

                /**
                 * Sets the value of the isLossyCompressed property.
                 * 
                 */
                public void setIsLossyCompressed(boolean value) {
                    this.isLossyCompressed = value;
                }

                /**
                 * Gets the value of the tileSize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTileSize() {
                    return tileSize;
                }

                /**
                 * Sets the value of the tileSize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTileSize(String value) {
                    this.tileSize = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContentItem">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Code">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentItem"
    })
    public static class PrimaryAnatomicStructure {

        @XmlElement(name = "ContentItem", required = true)
        protected ImageMetadata.PrimaryAnatomicStructure.ContentItem contentItem;

        /**
         * Gets the value of the contentItem property.
         * 
         * @return
         *     possible object is
         *     {@link ImageMetadata.PrimaryAnatomicStructure.ContentItem }
         *     
         */
        public ImageMetadata.PrimaryAnatomicStructure.ContentItem getContentItem() {
            return contentItem;
        }

        /**
         * Sets the value of the contentItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageMetadata.PrimaryAnatomicStructure.ContentItem }
         *     
         */
        public void setContentItem(ImageMetadata.PrimaryAnatomicStructure.ContentItem value) {
            this.contentItem = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Code">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valueType",
            "code"
        })
        public static class ContentItem {

            @XmlElement(name = "ValueType", required = true)
            protected String valueType;
            @XmlElement(name = "Code", required = true)
            protected ImageMetadata.PrimaryAnatomicStructure.ContentItem.Code code;

            /**
             * Gets the value of the valueType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueType() {
                return valueType;
            }

            /**
             * Sets the value of the valueType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueType(String value) {
                this.valueType = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link ImageMetadata.PrimaryAnatomicStructure.ContentItem.Code }
             *     
             */
            public ImageMetadata.PrimaryAnatomicStructure.ContentItem.Code getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageMetadata.PrimaryAnatomicStructure.ContentItem.Code }
             *     
             */
            public void setCode(ImageMetadata.PrimaryAnatomicStructure.ContentItem.Code value) {
                this.code = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "codeValue",
                "codingSchemeDesignator",
                "codeMeaning"
            })
            public static class Code {

                @XmlElement(name = "CodeValue", required = true)
                protected String codeValue;
                @XmlElement(name = "CodingSchemeDesignator", required = true)
                protected String codingSchemeDesignator;
                @XmlElement(name = "CodeMeaning", required = true)
                protected String codeMeaning;

                /**
                 * Gets the value of the codeValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeValue() {
                    return codeValue;
                }

                /**
                 * Sets the value of the codeValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeValue(String value) {
                    this.codeValue = value;
                }

                /**
                 * Gets the value of the codingSchemeDesignator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodingSchemeDesignator() {
                    return codingSchemeDesignator;
                }

                /**
                 * Sets the value of the codingSchemeDesignator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodingSchemeDesignator(String value) {
                    this.codingSchemeDesignator = value;
                }

                /**
                 * Gets the value of the codeMeaning property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeMeaning() {
                    return codeMeaning;
                }

                /**
                 * Sets the value of the codeMeaning property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeMeaning(String value) {
                    this.codeMeaning = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContentItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ConceptName">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentItem"
    })
    public static class ScannerMetadata {

        @XmlElement(name = "ContentItem", required = true)
        protected List<ImageMetadata.ScannerMetadata.ContentItem> contentItem;

        /**
         * Gets the value of the contentItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageMetadata.ScannerMetadata.ContentItem }
         * 
         * 
         */
        public List<ImageMetadata.ScannerMetadata.ContentItem> getContentItem() {
            if (contentItem == null) {
                contentItem = new ArrayList<ImageMetadata.ScannerMetadata.ContentItem>();
            }
            return this.contentItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ConceptName">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valueType",
            "conceptName",
            "text"
        })
        public static class ContentItem {

            @XmlElement(name = "ValueType", required = true)
            protected String valueType;
            @XmlElement(name = "ConceptName", required = true)
            protected ImageMetadata.ScannerMetadata.ContentItem.ConceptName conceptName;
            @XmlElement(name = "Text", required = true)
            protected String text;

            /**
             * Gets the value of the valueType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueType() {
                return valueType;
            }

            /**
             * Sets the value of the valueType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueType(String value) {
                this.valueType = value;
            }

            /**
             * Gets the value of the conceptName property.
             * 
             * @return
             *     possible object is
             *     {@link ImageMetadata.ScannerMetadata.ContentItem.ConceptName }
             *     
             */
            public ImageMetadata.ScannerMetadata.ContentItem.ConceptName getConceptName() {
                return conceptName;
            }

            /**
             * Sets the value of the conceptName property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageMetadata.ScannerMetadata.ContentItem.ConceptName }
             *     
             */
            public void setConceptName(ImageMetadata.ScannerMetadata.ContentItem.ConceptName value) {
                this.conceptName = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "codeValue",
                "codingSchemeDesignator",
                "codeMeaning"
            })
            public static class ConceptName {

                @XmlElement(name = "CodeValue", required = true)
                protected String codeValue;
                @XmlElement(name = "CodingSchemeDesignator", required = true)
                protected String codingSchemeDesignator;
                @XmlElement(name = "CodeMeaning", required = true)
                protected String codeMeaning;

                /**
                 * Gets the value of the codeValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeValue() {
                    return codeValue;
                }

                /**
                 * Sets the value of the codeValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeValue(String value) {
                    this.codeValue = value;
                }

                /**
                 * Gets the value of the codingSchemeDesignator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodingSchemeDesignator() {
                    return codingSchemeDesignator;
                }

                /**
                 * Sets the value of the codingSchemeDesignator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodingSchemeDesignator(String value) {
                    this.codingSchemeDesignator = value;
                }

                /**
                 * Gets the value of the codeMeaning property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeMeaning() {
                    return codeMeaning;
                }

                /**
                 * Sets the value of the codeMeaning property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeMeaning(String value) {
                    this.codeMeaning = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContentItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ConceptName">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Code">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentItem"
    })
    public static class StainMetadata {

        @XmlElement(name = "ContentItem", required = true)
        protected List<ImageMetadata.StainMetadata.ContentItem> contentItem;

        /**
         * Gets the value of the contentItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageMetadata.StainMetadata.ContentItem }
         * 
         * 
         */
        public List<ImageMetadata.StainMetadata.ContentItem> getContentItem() {
            if (contentItem == null) {
                contentItem = new ArrayList<ImageMetadata.StainMetadata.ContentItem>();
            }
            return this.contentItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ConceptName">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Code">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valueType",
            "conceptName",
            "code"
        })
        public static class ContentItem {

            @XmlElement(name = "ValueType", required = true)
            protected String valueType;
            @XmlElement(name = "ConceptName", required = true)
            protected ImageMetadata.StainMetadata.ContentItem.ConceptName conceptName;
            @XmlElement(name = "Code", required = true)
            protected ImageMetadata.StainMetadata.ContentItem.Code code;

            /**
             * Gets the value of the valueType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueType() {
                return valueType;
            }

            /**
             * Sets the value of the valueType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueType(String value) {
                this.valueType = value;
            }

            /**
             * Gets the value of the conceptName property.
             * 
             * @return
             *     possible object is
             *     {@link ImageMetadata.StainMetadata.ContentItem.ConceptName }
             *     
             */
            public ImageMetadata.StainMetadata.ContentItem.ConceptName getConceptName() {
                return conceptName;
            }

            /**
             * Sets the value of the conceptName property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageMetadata.StainMetadata.ContentItem.ConceptName }
             *     
             */
            public void setConceptName(ImageMetadata.StainMetadata.ContentItem.ConceptName value) {
                this.conceptName = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link ImageMetadata.StainMetadata.ContentItem.Code }
             *     
             */
            public ImageMetadata.StainMetadata.ContentItem.Code getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageMetadata.StainMetadata.ContentItem.Code }
             *     
             */
            public void setCode(ImageMetadata.StainMetadata.ContentItem.Code value) {
                this.code = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "codeValue",
                "codingSchemeDesignator",
                "codeMeaning"
            })
            public static class Code {

                @XmlElement(name = "CodeValue", required = true)
                protected String codeValue;
                @XmlElement(name = "CodingSchemeDesignator", required = true)
                protected String codingSchemeDesignator;
                @XmlElement(name = "CodeMeaning", required = true)
                protected String codeMeaning;

                /**
                 * Gets the value of the codeValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeValue() {
                    return codeValue;
                }

                /**
                 * Sets the value of the codeValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeValue(String value) {
                    this.codeValue = value;
                }

                /**
                 * Gets the value of the codingSchemeDesignator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodingSchemeDesignator() {
                    return codingSchemeDesignator;
                }

                /**
                 * Sets the value of the codingSchemeDesignator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodingSchemeDesignator(String value) {
                    this.codingSchemeDesignator = value;
                }

                /**
                 * Gets the value of the codeMeaning property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeMeaning() {
                    return codeMeaning;
                }

                /**
                 * Sets the value of the codeMeaning property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeMeaning(String value) {
                    this.codeMeaning = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodingSchemeDesignator" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CodeMeaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "codeValue",
                "codingSchemeDesignator",
                "codeMeaning"
            })
            public static class ConceptName {

                @XmlElement(name = "CodeValue", required = true)
                protected String codeValue;
                @XmlElement(name = "CodingSchemeDesignator", required = true)
                protected String codingSchemeDesignator;
                @XmlElement(name = "CodeMeaning", required = true)
                protected String codeMeaning;

                /**
                 * Gets the value of the codeValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeValue() {
                    return codeValue;
                }

                /**
                 * Sets the value of the codeValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeValue(String value) {
                    this.codeValue = value;
                }

                /**
                 * Gets the value of the codingSchemeDesignator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodingSchemeDesignator() {
                    return codingSchemeDesignator;
                }

                /**
                 * Sets the value of the codingSchemeDesignator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodingSchemeDesignator(String value) {
                    this.codingSchemeDesignator = value;
                }

                /**
                 * Gets the value of the codeMeaning property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodeMeaning() {
                    return codeMeaning;
                }

                /**
                 * Sets the value of the codeMeaning property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodeMeaning(String value) {
                    this.codeMeaning = value;
                }

            }

        }

    }

}
